name: Release

env:
  HUSKY: 0

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'packages/libs/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm --stream --filter "@constellar/*" run test:unit
      - name: Publish
        run: pnpm --stream --filter "@constellar/*" publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
