name: Release

env:
  HUSKY: 0

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'packages/libs/core/**'
      - 'packages/libs/jotai/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Build
        run: pnpm run build
      - name: Check types
        run: pnpm run test:types
      - name: Unit tests
        run: pnpm run test:coverage
      - name: Publish @constellar/core
        run: pnpm --filter "@constellar/core" publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
      - name: Publish @constellar/jotai
        run: pnpm --filter "@constellar/jotai" publish --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
